<a href="https://colab.research.google.com/github/mikieoo/big-data-analysis/blob/main/series_object.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df=pd.Series([781,650,705,406,580,450,550,640],
             index=['A','B','C','D','E','F','G','H'])

df

A    781
B    650
C    705
D    406
E    580
F    450
G    550
H    640
dtype: int64

In [ ]:
result = df[(df < 500) | (df > 700)]
result

A    781
C    705
D    406
F    450
dtype: int64

In [ ]:
result = df[df > df['B']]
result

A    781
C    705
dtype: int64

In [ ]:
result = df[df < 600].index
print(list(result))

['D', 'E', 'F', 'G']

In [ ]:
# 매출액이 600미만인 팀들의 매출액을 20% 증가
result = df[df < 600] * 1.2
result

D    487.2
E    696.0
F    540.0
G    660.0
dtype: float64

In [ ]:
print(df.mean())
print(df.sum())
print(df.std())

595.25
4762
125.77843330918972

In [ ]:
df[['A','C']] = [810,820]
df

A    810
B    650
C    820
D    406
E    580
F    450
G    550
H    640
dtype: int64

In [ ]:
df['J']=400
df

A    810
B    650
C    820
D    406
E    580
F    450
G    550
H    640
J    400
dtype: int64

In [ ]:
df.drop('J')

A    810
B    650
C    820
D    406
E    580
F    450
G    550
H    640
dtype: int64

In [ ]:
df2=df.copy()
df2=df + 500
print(df.describe())
print(df2.describe())

count      9.000000
mean     589.555556
std      157.581020
min      400.000000
25%      450.000000
50%      580.000000
75%      650.000000
max      820.000000
dtype: float64
count       9.000000
mean     1089.555556
std       157.581020
min       900.000000
25%       950.000000
50%      1080.000000
75%      1150.000000
max      1320.000000
dtype: float64